### PR TITLE
Translate Using TypeScript Page

### PR DESCRIPTION
**Pull request by mahmood601**
Finally 😄
It take from me alt of time, I hope that it will be empty from errors and misunderstanding 😁❤️

### CODE REVIEW

**Comment by A7med3bdulBaset** [comment]
@mahmood601 Why did you close that?

**Comment by mahmood601** [comment]
> @mahmood601 Why did you close that?

I don't know!
I'm beginner in using Github and git 😅

**Comment by mahmood601** [comment]
I don't have to close pull request and delete the branch, I have to send the changes on the same branch 🤦🏻‍♂️

**Comment by A7med3bdulBaset** [comment]
I saw you've already opened another pull request #526 

Read this comment https://github.com/reactjs/ar.react.dev/pull/521#issuecomment-1686745528
It's like a cheat sheet of git

**Comment by mahmood601** [comment]
> I saw you've already opened another pull request #526 
> 
> Read this comment https://github.com/reactjs/ar.react.dev/pull/521#issuecomment-1686745528
> It's like a cheat sheet of git

Thanks, I will read that sheet 😁

**Pull request closed without merging**
