### PR TITLE
Set the direction to `rtl` because Arabic is written from right to left.

### PR DESCRIPTION
**Pull request by A7med3bdulBaset**
# Fix Right and left directions issues

## What does this PR do?

- Add `direction: rtl;` to `[lang="ar"]` selector.
- Add `direction: ltr;` to code blocks.
- Exchange `padding-left`, `padding-right`, `margin-left`, `margin-right`, and `inset-inline-*` values if needed.
- Exchange `IconArrow` direction.
- Edit `text-left` to `text-right` if needed.

> This PR does not translate the content.

### CODE REVIEW

**Comment by A7med3bdulBaset** [comment]
Check failing is because of Prettier Formatting.

The `yarn ci-check` command which runs [`prettier:diff` which refers to `yarn nit:source`](https://github.com/reactjs/ar.react.dev/blob/main/package.json), throw an error saying `error Command failed with exit code 1`

It needs before to run:

```bash
npx prettier --write --list-different .
```

To format all files. Then, the `yarn ci-check` won't fail anymore.

**Comment by gaearon** [comment]
I'd like to propose that, if possible, RTL handling should be sent as a PR to the main `react.dev` repo. Then make it a setting here: https://github.com/reactjs/react.dev/blob/ad4f5c7c9555f65d6b889e85427ba3fdfa4e7159/src/siteConfig.js#L7

**Comment by A7med3bdulBaset** [comment]
> I'd like to propose that, if possible, RTL handling should be sent as a PR to the main `react.dev` repo. Then make it a setting here: https://github.com/reactjs/react.dev/blob/ad4f5c7c9555f65d6b889e85427ba3fdfa4e7159/src/siteConfig.js#L7

Ok

**Comment by A7med3bdulBaset** [comment]
> I'd like to propose that, if possible, RTL handling should be sent as a PR to the main `react.dev` repo. Then make it a setting here: https://github.com/reactjs/react.dev/blob/ad4f5c7c9555f65d6b889e85427ba3fdfa4e7159/src/siteConfig.js#L7

@gaearon
As Arabic users, we face challenges when reading the documentation due to the LTR settings.
So, I have submitted [a pull request](https://github.com/reactjs/react.dev/pull/6138) to the main `react.dev` branch.
I kindly request you to review the pull request or assign a maintainer to it ASAP

**Pull request closed without merging**
