### PR TITLE
WIP: Translate "Implementation Notes"

### PR DESCRIPTION
**Pull request by mriiad**
🚧 Work in progress

### CODE REVIEW

**Comment by atefBB** [comment]
This PR does not have any file change on it !
@mriiad Please check your work.

**Comment by mriiad** [comment]
As written in the description, the work is in progress but I created it as @3imed-jaberi asked for and to allow him to assign the suitable task to me.
@atefBB please feel free to add the needed labels (work-in-progress, help wanted, etc.), otherwise I will convert it to draft before getting all the work done but I guess this is not the most practical way.

**Comment by atefBB** [comment]
I think @3imed-jaberi means that you send a PR containing your work, not an empty one! Is that true @3imed-jaberi ?!

**Comment by mriiad** [comment]
Creating a PR labelled 'work-in-progress' would allow him to assign the concerned task to me so others won't ask to do it.
It's kind of reserving the task and notifying interested people that it's in progress.

Absolutely, there will be upcoming commits soon.

But, maybe I'm wrong and there's another way of work so I would like to thank you for these notes and I'm waiting for Imad's instructions.

**Comment by 3imed-jaberi** [comment]
Hello,
As @atefBB says. and I see that you will do that.
I assign you on #1 for "Implementation Notes"
> I think @3imed-jaberi means that you send a PR containing your work, not an empty one! Is that true @3imed-jaberi ?!

**Review by 3imed-jaberi — COMMENTED** [review]
@mriiad please don't forget to ping me when you are done here!

**Pull request closed without merging**
