### PR TITLE
[DONE]: Translation of Installation 

### PR DESCRIPTION
**Pull request by AbdulrehmanSuliman**
You can see below visual examples
image

image

image

image

image

I have a question regarding the sandbox section do I need to translate download, Fork, and reset as well?

### CODE REVIEW

**Comment by A7med3bdulBaset** [comment]
> I have a question regarding the sandbox section do I need to translate download, Fork, and reset as well?

No.

These are buttons embedded by CodeSandbox. Leave them as same.

**Comment by AbdulrehmanSuliman** [comment]
> > I have a question regarding the sandbox section do I need to translate download, Fork, and reset as well?
> 
> No.
> 
> These are buttons embedded by CodeSandbox. Leave them as same.

Then this page is ready, I don't need to do anything else ?

**Comment by A7med3bdulBaset** [comment]
Just translate the index in the `SidebarLearn.json` that match your page. Then someone from the maintainers will review it

**Comment by A7med3bdulBaset** [comment]
Notice You've edited 3 files other than your page. That is not a right approach.
Turn them back and there is a separated PR for handling rtl.

**Comment by AbdulrehmanSuliman** [comment]
> Notice You've edited 3 files other than your page. That is not a right approach. Turn them back and there is a separated PR for handling rtl.

You mean that for this PR I will return the the other files as they were and just edit in installation.md and SidebarLearn.json. Regarding the rtl handling am I supposed to handle it in another branch and create PR or someone else will handle it?

**Comment by AbdulrehmanSuliman** [comment]
> > You mean that for this PR I will return the the other files as they were and just edit in installation.md and SidebarLearn.json. Regarding the rtl handling am I supposed to handle it in another branch and create PR or someone else will handle it? @A7med3bdulBaset
> 
> Yes. Make yor PR for translation only so conflicts don't happen. Just translate two files:
> 
> * `installation.md`
> * a key in `sidebarlearn.json`
> 
> > Take this PR #473 as a guide example
> 
> There is already PR for rtl here #470

Translation only done in this PR. Thanks for helping

**Comment by A7med3bdulBaset** [comment]
The PR has been merged successfully.
Your translation is great. 
Go ahead and take another page.

**Pull request merged**
