### PR TITLE
[DONE] translate conditional rendering page

### PR DESCRIPTION
**Pull request by mrlahmar**
This PR should translate the conditional rendering page to Arabic.

### CODE REVIEW

**Review by A7med3bdulBaset — APPROVED** [review]
Please review my commit to this branch

**Review by A7med3bdulBaset — CHANGES_REQUESTED** [review]
Could you please translate the index of this page in `src/content/sidebarLearn.json`

**Comment by mrlahmar** [comment]
Hey, @A7med3bdulBaset,

Thank you for your feedback and improvements 🙏. I really appreciate your efforts. I have made the requested changes.

**Review by A7med3bdulBaset — APPROVED** [review]

**Comment by A7med3bdulBaset** [comment]
Thanks for your contribution
You can now choose another page to translate

**Pull request merged**
